output: docs
clean: true
exclude: [Packages, Carthage]
author: David Ask
github_url: https://github.com/davidask/StateViewController
github_file_prefix: https://github.com/davidask/StateViewController/tree/master
readme: README.md
theme: fullwidth